### ISSUE TITLE
issue with building SSH action project

### ISSUE THREAD

**Issue by meirwah** [openscore/score-actions#1]
this seems like the issue:
[ERROR] Failed to execute goal on project score-ssh: Could not resolve dependencies for project io.openscore.content:score-ssh:jar:0.0.8-SNAPSHOT: The following artifacts could not be resolved: com.jcraft:jcterm:jar:0.0.11, bouncycastle:bcprov-jdk15:jar:144: Failure to find com.jcraft:jcterm:jar:0.0.11 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]

Look at travis CIO for more info :   
https://travis-ci.org/openscore/score-content/builds/45847996

**Comment by meirwah** [comment]
issue is with relying on dependencies that are not present in maven central... this is an urgent matter!!!
and this is what causing right now to both content and slang builds to fail on travis.. @octavian-h @ioanvranauhp @meshipeer @orius123

**Comment by orius123** [comment]
Where does internal nexus fetches those dependencies than? Did we uploaded manually? 
They don't look like hp artifacts..
Did we uploaded them?

**Comment by meirwah** [comment]
uploaded manually :(
