### ISSUE TITLE
SSH - agent forwarding mechanism

### ISSUE THREAD

**Issue by Bonczidai** [openscore/score-actions#36]
Our current use case relies on the SSH action and it needs the agent forwarding mechanism. Usually you enable this by -A option: `ssh -A user@host`. I observed that it can be set in the code in class `SSHServiceImpl` in `runShellCommand` method:

```
((ChannelShell) channel).setAgentForwarding(true);
```

Could you make the necessary changes in the code (extract an input that specifies to use agent forwarding or not)?

**Comment by ioanvranau** [comment]
merged the fix to the master. We need a release on the maven central in order to update the version in  score-language

**Comment by Bonczidai** [comment]
@hararzafrir could you please release a new version of score-actions in maven-central, so we can update the dependency in score-language?

**Comment by hararzafrir** [comment]
Sure,
Is it required to have all the modules (mail, http-client, utilities)? or just the SSH

**Comment by hararzafrir** [comment]
@Bonczidai, Just tried it, but it failed because it lacks the sources.jar and javadoc.jar...
I will add this change (pom.xml changes) and try to release once again.
I will let you know when it is ready

**Comment by meirwah** [comment]
can we merge it know @hararzafrir ?

**Comment by hararzafrir** [comment]
@Bonczidai,@meirwah, merged and released to Maven Central.

**Comment by Bonczidai** [comment]
fixed by #38
